/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MetodoBiseccion;

import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gustavo
 */
public class GUImain extends javax.swing.JFrame {

    public double limIzq;
    public double limDer;
    public double error;
    public String Formula;
    DefaultTableModel modelo;

    /**
     * Creates new form main
     */
    public GUImain() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jtxtLi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtLd = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtporciento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAcerca = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnRelizar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jtxtFormula = new javax.swing.JTextField();
        btnAviso = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtobligatorio1 = new javax.swing.JLabel();
        txtobligatorio2 = new javax.swing.JLabel();
        txtobligatorio3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Iteracion #", "Xa", "Xb", "Xr", "Fa", "Fb", "Fxr", "Er"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Limite izquierdo:");

        jLabel2.setText("Limite derecho:");

        jtxtLd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtLdActionPerformed(evt);
            }
        });

        jLabel3.setText("Error maximo:");

        jtxtporciento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtporcientoActionPerformed(evt);
            }
        });

        jLabel4.setText("%");

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel5.setText("Metodo Biseccion");

        btnAcerca.setText("Acerca de");
        btnAcerca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRelizar.setText("Realizar");
        btnRelizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRelizarActionPerformed(evt);
            }
        });

        jLabel6.setText("Formula:");

        btnAviso.setText("AVISO");
        btnAviso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvisoActionPerformed(evt);
            }
        });

        jButton3.setText("Limpiar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("F(x) =");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnSalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnAcerca)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(1, 1, 1)
                                        .addComponent(jtxtFormula, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jtxtLi, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(1, 1, 1)
                                        .addComponent(txtobligatorio1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jtxtLd))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtobligatorio2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(61, 61, 61)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jtxtporciento, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel4)))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtobligatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAviso)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                                        .addComponent(btnRelizar)))))
                        .addGap(14, 14, 14))))
            .addGroup(layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(txtobligatorio1)
                    .addComponent(txtobligatorio2)
                    .addComponent(txtobligatorio3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtLi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtporciento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnAviso, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(btnRelizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtFormula)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAcerca, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtporcientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtporcientoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtporcientoActionPerformed

    private void btnAcercaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null, ("Glosaro:\n Iteracion = i#\n X izquierda = Xa \n X derecha =Xb \n X media = Xr\n F(x) izquierda = Fa \n F(x) derecha = Fb \n F(x) media = Fxr"));
        JOptionPane.showMessageDialog(null, "Creado por:\n Gustavo Martinez Licona \n Gabino Arteaga Del Angel ");
    }//GEN-LAST:event_btnAcercaActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRelizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRelizarActionPerformed
        // TODO add your handling code here:
        try{
        String info[] = {"Iteracion #", "Xa", "Xb", "Xr", "Fa", "Fb", "Fxr", "Er"};
        Double datos1[][] = {};
            if (jtxtLi.getText() == null) {
                txtobligatorio1.setText("\033[31m *");
                txtobligatorio2.setText("*");
                txtobligatorio3.setText("*");
            }else if (jtxtLd.getText() == null) {
                txtobligatorio1.setText("*");
                txtobligatorio2.setText("\033[31m *");
                txtobligatorio3.setText("*");
            }else if (jtxtporciento.getText() == null) {
                txtobligatorio1.setText("*");
                txtobligatorio2.setText("*");
                txtobligatorio3.setText("\033[31m *");
            }
        modelo = new DefaultTableModel(datos1, info);
        jTable1.setModel(modelo);
        limIzq = Double.valueOf(jtxtLi.getText());
        limDer = Double.valueOf(jtxtLd.getText());
        error = Double.valueOf(jtxtporciento.getText());
        error = (error / 100);
        biseccion(limIzq, limDer, error);
        }catch(Exception e){
         JOptionPane.showMessageDialog(null, "ocurrio un error en la captura de datos");
        }
    }//GEN-LAST:event_btnRelizarActionPerformed

    private double f(double x) {

        double fx = 0;
        //Aqui coloca la funcion
        //metodo para calcular F(x)

            fx = (Math.pow(x, 10) - 1);
            return fx;

    }

    public void biseccion(double limIzq, double limDer, double error) {
        double xI = limIzq;
        double xD = limDer;
        double eMax = error;
        double fxI = f(xI);
        double fxD = f(xD);
        double xM = xMedia(xI, xD);
        double fxM = f(xM);
        double Er = 0;
        double xManterior = 0;
        int contador = 1;

        //Verifica si existe raiz entre xi y xd
        if ((fxI > 0 && fxD > 0) || ((fxI < 0 && fxD < 0))) {
            System.out.println("Sin raíces en este intervalo");
            return;
        }

        System.out.println("Glosaro:\n Iteracion = i#\n X izquierda = Xa \n X derecha =Xb \n X media = Xr"
                + "\n F(x) izquierda = Fa \n F(x) derecha = Fb \n F(x) media = Fxr");

        System.out.println(" \ni# \t Xa \t Xb \t Xr \t Fa \t Fb \t Fxr \t Ea");

        while (Math.abs(fxM) >= eMax) {
            // %.3f = a la delimitacion de ddecimales despues de el punto
            // \t = espacio de tabulador
            // \n = salto de linea
            Object datos[] = {contador, xI, xD, xM, fxI, fxD, fxM, Er};
            modelo.addRow(datos);
            System.out.print(contador);
            System.out.print("\t");
            System.out.printf("%.3f", xD);
            System.out.print("\t");
            System.out.printf("%.3f", xI);
            System.out.print("\t");
            System.out.printf("%.3f", xM);
            System.out.print("\t");
            System.out.printf("%.3f", fxI);
            System.out.print("\t");
            System.out.printf("%.3f", fxD);
            System.out.print("\t");
            System.out.printf("%.3f", fxM);
            System.out.print("\t");
            System.out.printf("%.3f", Er);
            System.out.print("% \n");

            //Pasa el valor de FxM a xI o xD
            if (fxM * fxI > 0) {
                xI = xM;
            } else {
                xD = xM;
            }
            //llamada a los metodos
            fxI = f(xI);
            fxD = f(xD);

            xManterior = xM;
            xM = xMedia(xI, xD);
            fxM = f(xM);

            contador++;
            if (contador >= 2) {
                Er = (xM - xManterior) / xM;
                Er = Er * 100;
                if (Er < 0) {
                    Er = Er * -1;
                }
            }

        }
        Object datos[] = {contador, xI, xD, xM, fxI, fxD, fxM, Er};
        modelo.addRow(datos);
        System.out.print(contador);
        System.out.print("\t");
        System.out.printf("%.3f", xD);
        System.out.print("\t");
        System.out.printf("%.3f", xI);
        System.out.print("\t");
        System.out.printf("%.3f", xM);
        System.out.print("\t");
        System.out.printf("%.3f", fxI);
        System.out.print("\t");
        System.out.printf("%.3f", fxD);
        System.out.print("\t");
        System.out.printf("%.3f", fxM);
        System.out.print("\t");
        System.out.printf("%.3f", Er);
        System.out.print("% \n");
    }

    private double xMedia(double x1, double x2) {
        //metodo para calcular xM (en biseccion) o  el promedio de ellos dos
        return ((x1 + x2) / 2);
    }
    private void btnAvisoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvisoActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(null, "Para poner una formula por el moento es necesario solo ingresar operaciones basicas (+,-,/,*) de funciones de una incognita (solo X)");

    }//GEN-LAST:event_btnAvisoActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jtxtLdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtLdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtLdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUImain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUImain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAcerca;
    private javax.swing.JButton btnAviso;
    private javax.swing.JButton btnRelizar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jtxtFormula;
    private javax.swing.JTextField jtxtLd;
    private javax.swing.JTextField jtxtLi;
    private javax.swing.JTextField jtxtporciento;
    private javax.swing.JLabel txtobligatorio1;
    private javax.swing.JLabel txtobligatorio2;
    private javax.swing.JLabel txtobligatorio3;
    // End of variables declaration//GEN-END:variables
}
